# Generated by Django 2.1.5 on 2019-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190117_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='insta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='locate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='subphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
